// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moon.Models;

namespace Moon_.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Moon.Entities.Files", b =>
                {
                    b.Property<string>("DocumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<string>("CourseCode");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<byte[]>("DataFiles");

                    b.Property<string>("FileType")
                        .HasMaxLength(100);

                    b.Property<string>("Lecturer");

                    b.Property<int>("Likes");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("Title");

                    b.Property<string>("ownerId");

                    b.HasKey("DocumentId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Moon.Entities.Post", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("category");

                    b.Property<string>("courseCode");

                    b.Property<DateTime>("dateTime");

                    b.Property<byte[]>("document");

                    b.Property<string>("lecturer");

                    b.Property<int>("likes");

                    b.Property<string>("ownerId");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Moon.Entities.Student", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("department");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.Property<string>("surname");

                    b.HasKey("id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
